### ISSUE TITLE
Unknown error occurred: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by schmir** [rubik/pyg#108]
I'm running the following with the sources to bbfreeze in the current directory:

[py27]  ~/ % pyg install bbfreeze
Installing /home/ralf/bbfreeze
Installing bbfreeze
Running setup.py egg_info for bbfreeze
Running setup.py install for bbfreeze
Installing dependencies...
        altgraph>=0.6.7 is already installed, use -A, --upgrade-all to upgrade dependencies
Unknown error occurred: 'str' object has no attribute 'name'

**Comment by fdev31** [comment]
Thanks for this report,
Since I can't reproduce, could you try with that version:

https://github.com/rubik/pyg/zipball/master

and this one:

https://github.com/rubik/pyg/zipball/develop

?

**Comment by schmir** [comment]
fdev31
reply@reply.github.com
writes:

> Thanks for this report,
> Since I can't reproduce, could you try with that version:
> 
> https://github.com/rubik/pyg/zipball/master
> 
> and this one:
> 
> https://github.com/rubik/pyg/zipball/develop

sure. same problem.

If I run git clean in bbfreeze the problem is gone. Running setup.py
build in bbfreeze makes the problem reappear.

**Comment by fdev31** [comment]
Interestig, we will investigate

**Comment by rubik** [comment]
Thanks for testing! :)
Can you try with the --debug flag? (like this: pyg --debug install bblfreeze)

Thank you!

**Comment by schmir** [comment]
rubik
reply@reply.github.com
writes:

> Thanks for testing! :)
> Can you try with the --debug flag? (like this: pyg --debug install bblfreeze)

sure:

,----[ _eshell_ ]
| Welcome to the Emacs shell
| 
| ~ $ pyg --debug install bbfreeze
| Installing /home/ralf/bbfreeze
| Installing bbfreeze
| Running setup.py egg_info for bbfreeze
| debug: virtualenv detected
| Running setup.py install for bbfreeze
| debug: virtualenv detected
| bbfreeze installed successfully
| ~ $ pyg --debug install bbfreeze
| Installing /home/ralf/bbfreeze
| Installing bbfreeze
| Running setup.py egg_info for bbfreeze
| debug: virtualenv detected
| Running setup.py install for bbfreeze
| debug: virtualenv detected
| Installing dependencies...
|         altgraph>=0.6.7 is already installed, use -A, --upgrade-all to upgrade dependencies
| Traceback (most recent call last):
|   File "/home/ralf/local/bin/pyg", line 9, in <module>
|     load_entry_point('pyg==0.8a', 'console_scripts', 'pyg')()
|   File "/home/ralf/py27/lib/python2.7/site-packages/pyg-0.8a-py2.7.egg/pyg/**init**.py", line 28, in main
|     parser.dispatch(argv=argv)
|   File "/home/ralf/py27/lib/python2.7/site-packages/argh-0.14.0-py2.7.egg/argh/helpers.py", line 304, in dispatch
|     return dispatch(self, _args, *_kwargs)
|   File "/home/ralf/py27/lib/python2.7/site-packages/argh-0.14.0-py2.7.egg/argh/helpers.py", line 205, in dispatch
|     for line in lines:
|   File "/home/ralf/py27/lib/python2.7/site-packages/argh-0.14.0-py2.7.egg/argh/helpers.py", line 281, in _execute_command
|     for line in result:
|   File "/home/ralf/py27/lib/python2.7/site-packages/argh-0.14.0-py2.7.egg/argh/helpers.py", line 264, in _call
|     result = args.function(args)
|   File "/home/ralf/py27/lib/python2.7/site-packages/pyg-0.8a-py2.7.egg/pyg/parser/parser.py", line 99, in install
|     args_manager['install']['ignore'])
|   File "/home/ralf/py27/lib/python2.7/site-packages/pyg-0.8a-py2.7.egg/pyg/parser/_opts.py", line 94, in install_func
|     _install_package_from_name(package, ignore)
|   File "/home/ralf/py27/lib/python2.7/site-packages/pyg-0.8a-py2.7.egg/pyg/parser/_opts.py", line 65, in _install_package_from_name
|     return Installer.from_dir(path)
|   File "/home/ralf/py27/lib/python2.7/site-packages/pyg-0.8a-py2.7.egg/pyg/inst.py", line 192, in from_dir
|     Installer._install_deps(reqset)
|   File "/home/ralf/py27/lib/python2.7/site-packages/pyg-0.8a-py2.7.egg/pyg/inst.py", line 84, in _install_deps
|     logger.success('Finished installing dependencies for {0}', rs.comes_from.name)
| AttributeError: 'str' object has no attribute 'name'
`----

**Comment by rubik** [comment]
Oops I forgot that github closes issues automatically...

**Comment by rubik** [comment]
Do you still notice the problem? (The above commit should fix that.) :)

**Comment by schmir** [comment]
rubik
reply@reply.github.com
writes:

> Do you still notice the problem?

it's working in the develop branch.

---

Cheers,
Ralf

**Comment by rubik** [comment]
Very good! :) I'll merge changes before next bugfix release.
Thank you for testing! ;)
