### ISSUE TITLE
Adding VCS support

### ISSUE THREAD

**Issue by rubik** [rubik/pyg#11]
We should adding the possibility to install in editable mode from a VCS, like Pip.

**Comment by rubik** [comment]
I'm working on it. I've seen that Pip uses the command-line programs like git, hg, bzr to retrieve the code from a VCS. Is there a simpler way?

**Comment by Malex** [comment]
Perhaps these could be useful for git:
http://gitorious.org/git-python
https://launchpad.net/dulwich

**Comment by rubik** [comment]
Thank you for the link, I checked them but they don't offer something to retrieve code from an online repo. I tried to write some code:
https://github.com/rubik/pyg/commit/848aed9840d8aa07a523e1460a2a70323b70a90d
