### ISSUE TITLE
Intergration

### ISSUE THREAD

**Issue by jkbbwr** [rubik/pyg#111]
Hey remember python-forum? We are working on an IDE and we are looking for tools to go into it, we were wondering if you would like to intergrate pyg into our project.

**Comment by rubik** [comment]
Hi Jbowyer, thank you! :)
I'll check the project on the forum! I'd be glad to add Pyg to the IDE. Where should I post?
Thank you for the opportunity.

**Comment by jkbbwr** [comment]
Just wait a bit longer for two more features to become developed and then we can start work on your intergration.

**Comment by rubik** [comment]
Ok, thank you!
