### ISSUE TITLE
update command: spawn a new process

### ISSUE THREAD

**Issue by rubik** [rubik/pyg#114]
I was wondering if it would be useful to spawn a new process (through the multiprocessing module) when we install a new package. Some packages (for example non-pure Python ones) can take really long to `egg_info` and `install`, and during this we could continue to look for updates.
Here is the idea: we keep looking for updates and when the user answer `yes` we spawn a new process for the installation.

**Comment by rubik** [comment]
I finally found a way to make it work. I'll commit that tomorrow.

**Comment by fdev31** [comment]
Looks like an interesting improvement :)

**Comment by rubik** [comment]
Yes, but it doesn't work yet! ;)
I'm thinking about using a multiprocessing.Pool instead of creating a Process for every package.

**Comment by rubik** [comment]
Ok, now we have to keep track of the checked packages, to display the progress. I think we can do this with multiprocessing.Value

**Comment by rubik** [comment]
Good. It works fine for me. Just another thing: when displaying progress if the new line is shorter than the previous one it gets ugly...

Example:

```
[100.0% - Mako, 66 / 66],  65 / 66]
```

**Comment by fdev31** [comment]
You can assume you have a MAX_LINE_WIDTH and echo "\r" + (" "*MAX_LINE_WIDTH)  + "\r" or something before your own print (it will just blank the line)
or try to get the terminal width (http://stackoverflow.com/questions/566746/how-to-get-console-window-width-in-python). What do you think ?

**Comment by rubik** [comment]
I found a simple function to get the console width, I think it can work now.
While I was running the update to check whether the improvement worked I got (at the end of the updating process) a weird error:

```
Updating finished successfully                                                  
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/miki/pyg/pyg/inst.py", line 485, in _clean
    shutil.rmtree(dirs.keys()[0])
  File "/usr/lib/python2.7/shutil.py", line 236, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 234, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/tmp/pyg-lC45m_-record'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/miki/pyg/pyg/inst.py", line 485, in _clean
    shutil.rmtree(dirs.keys()[0])
  File "/usr/lib/python2.7/shutil.py", line 236, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 234, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/tmp/pyg-lC45m_-record'
```

It says temporary directories does not exists anymore, why?

**Comment by fdev31** [comment]
Maybe the code is already removing it while atexit.register was called to delete that temporary folder, isn't that a conflict with the code I wrote (which automates temporary folders removal on exit), you can remove it from the list of files to delete btw, I'm a bit sick now so I'll probably not look the code to refresh my memory but be I bellieve it's related :)

**Comment by rubik** [comment]
it's the _clean method... it removes temporary directories created by the Updater and when atexit is called these directories no longer exist. We can add a check in the atexit function-.
