### ISSUE TITLE
Add installing options

### ISSUE THREAD

**Issue by Malex** [rubik/pyg#16]
As many other package manager (i.e portage) we could implement options to specify what to install:
for instance, "-doc" if I don't want to install docs files, "-scripts" if I want to install only the lib and not the scripts (i.e a package has a file which should be put in /usr/bin and I don't want to).

Besides we could set an enviroment variable (or through a configuration file) to set which options we want to use "system-wide"
(for example, I may want not to have any doc file installed.

**Comment by rubik** [comment]
Thank you Malex, I think this is a very good idea. We can implement an installation without scripts: it should be easy. I think docs files are not a problem because a standard installation of a Python package shouldn't install them.

Thank you,
rubik

**Comment by rubik** [comment]
I tried to implement it here:
https://github.com/rubik/pyg/commit/2c1a905af08460cf4e2e3a2f8e20e04acff0d9f2

**Comment by Malex** [comment]
Well, then we could implement a "doc" option to install them (it's an example of course, many packages could have optional plugin installing).
Anyway, good work (I saw you assigned this issue to yourself)

**Comment by Malex** [comment]
(didn't want to close, just by mistake asd)

**Comment by rubik** [comment]
I don't really know what "assign an issue" means... If you want you can assign it to yourself.

**Comment by rubik** [comment]
But Pyg is a package manager for Python packages, that don't define doc files.

**Comment by rubik** [comment]
I think there aren't other installing options. If you have any suggestions don't hesitate to open new issues!
