### ISSUE TITLE
Installation from url does not work when URL does not end with a file extension

### ISSUE THREAD

**Issue by rubik** [rubik/pyg#40]
For example, this will not work:

```
$ pyg install https://github.com/rubik/tarball/master
```

But it IS an archive! Pyg should check whether the given file is an archive and then install it...

**Comment by Malex** [comment]
well, you could parse the server response, since in there's the content-type header, which says you whether it's an archive. And if not, at such time you can stop downloading that.

**Comment by rubik** [comment]
Thank you Malex, that is really a good idea!
