### ISSUE TITLE
pyg install --user does not work

### ISSUE THREAD

**Issue by rubik** [rubik/pyg#64]
Even when you pass the `--user` option Pyg installs packages in the default `site-packages`...

**Comment by fdev31** [comment]
Doesn't work for me...

**Comment by fdev31** [comment]
Sorry, my mistake, I was guessing about the .pth alteration problem to not be fatal...

**Comment by rubik** [comment]
Ok, are you sure it works for you?

**Comment by fdev31** [comment]
Hum, I tested again :)

```
pyg install -u .
```

Works but still require system-level permissions (/usr/local/lib/python2.7/site-packages) which is wrong, isn't it ?
