### ISSUE TITLE
Console output not always very clear

### ISSUE THREAD

**Issue by fdev31** [rubik/pyg#72]
for instance, `pyg -h` will show something like this:

```

usage: pyg [-h] [-d] [--verbose] [-v]

           {search,shell,help,list,update,remove,freeze,link,bundle,install,download,unlink,check}
           ...

positional arguments:
  {search,shell,help,list,update,remove,freeze,link,bundle,install,download,unlink,check}
    install
    remove
    freeze
    link
    unlink
    list
    search
    check
    download
    update
    shell
    bundle
    help
```

Note that the list of commands is shown 3 times, and never really documented...

Added to that, I think it could be a good idea to support color output if available (I like the "colorama" module for that...), what do you think ?

**Comment by rubik** [comment]
It's not a bad idea, but we need to replace default argparse's HelpFormatter. It shouldn't be too difficult.
What do you think the --help should output?

**Comment by fdev31** [comment]
Ok, I think something like that is pretty:

```

usage: pyg [-h] [-d] [--verbose] [-v] [command] args...

Available commands:
    install [-eUAngu] [-i <url>] [-d <path>] [--no-scripts] [--no-data] package...
             Installs a package
    remove [-h] [-r <path>] [-y] [-i] package...
             Uninstall a package
   [...]              

```

**Comment by rubik** [comment]
Ok, I never used argparse.HelpFormatter or what it is, so I have to experiment a bit.

**Comment by fdev31** [comment]
Even just a short description of commands (without arguments documentation) would be fine :)

**Comment by rubik** [comment]
I finally found out that we need to subclass HelpFormatter.format_help.

**Comment by rubik** [comment]
Don't check that commit it is wrong! See:
https://github.com/rubik/pyg/issues/73

**Comment by rubik** [comment]
Ok, I wrote just the basis. We have to set `parser.formatter_class` at the bottom because the formatter needs to know what the parser arguments are. Check my next commit.

**Comment by fdev31** [comment]
I think this is already a very nice output :)
What is still lacking to you ?

**Comment by rubik** [comment]
I don't know... Maybe we could add colors, as you suggested.

**Comment by rubik** [comment]
Colors are troublesome: terminal background can be different, and someone can have it dark, someone bright, so how do we choose the colors?

**Comment by fdev31** [comment]
I agree, I see my ~/.pyg file is empty,
but if we have a configuration file we could disable color (for those who have the proper module but don't want to use it) and allow customization (for instance for: error, warning, success, standard).
If it's something you can't disable it can really be annoying I agree, and that's probably not a priority as well :P

**Comment by rubik** [comment]
Yes, good point. That is really a good idea!

**Comment by fdev31** [comment]
I'll probably handle the colored output / config on my free time to relax :)

**Comment by rubik** [comment]
Ok, I think the simplest way to do it is to extend the load method of pyg.core.ArgsManager

**Comment by rubik** [comment]
Do you want to add colors for the help formatting?

**Comment by fdev31** [comment]
Hm.... I don't think it's necessary, the output looks pretty clear to me, don't you think ?

**Comment by rubik** [comment]
Yes, now Pyg has a nicer help than before. Ok, I think we are almost ready for Pyg 0.7! (Only one issue-to-fix remaining)
