### ISSUE TITLE
AttributeError: 'module' object has no attribute 'getsitepackages'

### ISSUE THREAD

**Issue by jbholman** [rubik/pyg#75]
I did a fresh install of Python 2.7.  I then downloaded virtualenv-1.6.1.tar.gz.  Unzipped and installed virtualenv with 

```
python setup.py install.  
```

I then did the following:
    python -m virtualenv --no-site-packages testenv
    cd test2
    pip install pyg
    pyg shell

At the last part, I get the following error:

(test2) C:\Documents and Settings\sfgrgt\My Documents\Downloads\test2\Scripts>py
g shell
Traceback (most recent call last):
  File "C:\Documents and Settings\sfgrgt\My Documents\Downloads\test2\Scripts\py
g-script.py", line 8, in <module>
    load_entry_point('pyg==0.6', 'console_scripts', 'pyg')()
  File "C:\Documents and Settings\sfgrgt\My Documents\Downloads\test2\lib\site-p
ackages\pyg__init__.py", line 15, in main
    from pyg.core import PygError, InstallationError, AlreadyInstalled
  File "C:\Documents and Settings\sfgrgt\My Documents\Downloads\test2\lib\site-p
ackages\pyg\core.py", line 11, in <module>
    from pyg.locations import EASY_INSTALL, INSTALL_DIR, BIN, USER_SITE
  File "C:\Documents and Settings\sfgrgt\My Documents\Downloads\test2\lib\site-p
ackages\pyg\locations.py", line 46, in <module>
    INSTALL_DIR = site.getsitepackages()[0]
AttributeError: 'module' object has no attribute 'getsitepackages'

I'm on windows XP with python 2.7.1

**Comment by jbholman** [comment]
problem is fixed when i checked out latest version of pyg from source.  sorry about that.  i was using the version that i installed from pip.

**Comment by rubik** [comment]
Don't worry! :) This will be fixed in version 0.7. fdev31 fixed that in this commit:
https://github.com/rubik/pyg/commit/e92b1d5688ac2d31f17cea33cc91d4234dad15d9

Thank you!
