### ISSUE TITLE
Allow installing eggs with a different Python version

### ISSUE THREAD

**Issue by rubik** [rubik/pyg#76]
Sometimes a package does not have right eggs for your Python installation. For example, the package `eggchecker` only has two eggs:
- `eggchecker-0.1.3dev-py2.4.egg`
- `eggchecker-0.1.3dev-py2.5.egg`

If I really want to install one of them I should be able to do it. So I was thinking about adding a new option, like `--force-egg-install`, or something.
And one more thing: the user will choose the egg to install or Pyg?

**Comment by fdev31** [comment]
Supporting both methods (from .egg file or from pypi) is probably a good idea (the difference is just the fetching/or not), with something like --ignore-version ? It should probably check if the egg contains binary data or not as well... the filename is not always correct according to that (it may contain platform-specific name without platform-specific code).

+1 on this but with little priority.

**Comment by rubik** [comment]
Ok, thank you for your suggestions.

**Comment by rubik** [comment]
But how do we check whether the egg contains binaries?

**Comment by fdev31** [comment]
The simple way would be to know "common" binary extensions (.so .dll) and then check for that in the .egg content I suppose.

**Comment by rubik** [comment]
Now there is another problem: this package requires `pyflakes>=0.2.1,==dev`. We cannot manage this requirements.

**Comment by fdev31** [comment]
Why ? I don't think "dev" version are supported at all... but for the version it's ok, right ?
If I'm right, then we "just" need to add support for dev versions and then improve the requirements parser to allow multiple requirements for the same package...

**Comment by rubik** [comment]
At this point I think we should take advantage of pkg_resources.Requirement.parse to parse our requirements...

**Comment by rubik** [comment]
I'll open a new issue, but I leave that for Pyg 0.8.

> The simple way would be to know "common" binary extensions (.so .dll) and then check for that in the .egg content I suppose.

Yes but what if we haven't downloaded it yet? We cannot download every egg in order to check it! :)

**Comment by rubik** [comment]
I've just discovered that when you install a local egg Pyg does not check its Python version. What should we do?

**Comment by fdev31** [comment]
```
Yes but what if we haven't downloaded it yet? We cannot download every egg in order to check it! :)
```

Hum... I think the check has to be _after_ download. To me it's preferable to fail after a download than not allowing something that should work...

```
I've just discovered that when you install a local egg Pyg does not check its Python version. What should we do?
```

Maybe that is the right choice, let the user install any egg and remove it in case it's not working... Direct install of eggs can be quite dummy, only "remote" install should avoid conflicts/bad interpreter/etc as much as possible. Don't you think ? (or maybe I don't get the whole problem)

**Comment by rubik** [comment]
> Maybe that is the right choice, let the user install any egg and remove it in case it's not working... Direct install of eggs can be quite dummy, only "remote" install should avoid conflicts/bad interpreter/etc as much as possible. Don't you think ? (or maybe I don't get the whole problem)

Yes you are right. The user can install/remove whatever he wants.

> Hum... I think the check has to be after download. To me it's preferable to fail after a download than not allowing something that should work...

I don't think so. :) The check cannot be after download, because it would take too much time. Take, for example, the `eggchecker` package: it has 2 "bad" eggs. Downloading and checking them would take too much time IMHO.

**Comment by rubik** [comment]
I think we can close this issue now, we can re-open it for Pyg 0.8 if we realize that needs to be improved.
