### ISSUE TITLE
Improve uninstaller's file-detection

### ISSUE THREAD

**Issue by rubik** [rubik/pyg#77]
`pyg.inst.Uninstaller` does not uninstall `*.so` files, for example.

**Comment by fdev31** [comment]
Isn't that a bug ?
Do you mean it won't remove .so files of some package or it won't remove .so only packages ?

**Comment by rubik** [comment]
It doesn't look for *.so files, so it doesn't remove them. I don't know if that is a bug.

**Comment by fdev31** [comment]
But shouldn't it look for all installed files instead of filtering ? What is the reason of such a filter ?

**Comment by rubik** [comment]
There is no filter. The uninstaller simply looks for certain files following the specified patterns:

```
# Egg files
uninstall_re = re.compile(r'{0}(-(\d\.?)+(\-py\d\.\d)?\.(egg|egg\-info))?$'.format(self.name), re.I)
# Modules (.py) or packages
uninstall_re2 = re.compile(r'{0}(?:(\.py|\.pyc))'.format(self.name), re.I)
```
