### ISSUE TITLE
Allow comments in Pyg configuration files

### ISSUE THREAD

**Issue by rubik** [rubik/pyg#82]
Like this:

```
[global]
# I don't want colors
no_colors = True

[install]
# this is my local package index
index_url = 'http://my/url' # don't use on other systems
```

**Comment by fdev31** [comment]
Are you sure that's not already working ?
Here it looks like I can...

**Comment by rubik** [comment]
Oh yes, I didn't notice that. I think it's because ConfigParser automatically skip comments (either # or ; ).

EDIT: Yes, I found this in the docs:

> Lines beginning with '#' or ';' are ignored and may be used to provide comments.

So it seems we can close the issue! :)
