### ISSUE TITLE
Pyg can be surprising dealing some exceptions

### ISSUE THREAD

**Issue by fdev31** [rubik/pyg#88]
```
# make venv
fab@fab-1015PN:~/progs/pyg% virtualenv /tmp/foo --no-site-packages                                                                      
# activate & check it
fab@fab-1015PN:~/progs/pyg% source /tmp/foo/bin/activate                                                                                
(foo)fab@fab-1015PN:~/progs/pyg% ls /tmp/foo/lib/python2.7/site-packages                                                                
easy-install.pth  pip-1.0.1-py2.7.egg  setuptools-0.6c11-py2.7.egg  setuptools.pth
(foo)fab@fab-1015PN:~/progs/pyg% python setup.py develop
[...]
(foo)fab@fab-1015PN:~/progs/pyg% ls /tmp/foo/lib/python2.7/site-packages                                                                
argh-0.14.0-py2.7.egg  pip-1.0.1-py2.7.egg     pyg.egg-link         setuptools.pth
easy-install.pth       pkgtools-0.6-py2.7.egg  setuptools-0.6c11-py2.7.egg
(foo)fab@fab-1015PN:~/progs/pyg% cd /tmp/foo
(foo)fab@fab-1015PN:/tmp/foo% pyg install hg-git
Loading options from /home/fab/.pyg/pyg.conf
Looking for hg-git releases on PyPI
Best match: hg-git==0.2.6
Downloading hg-git [100% - 12.4 Kb / 12.4 Kb]             
Checking md5 sum
Running setup.py egg_info for hg-git
Running setup.py install for hg-git
Installing dependencies...
Installing dulwich>=0.6.0 (from hg-git)
        Looking for dulwich releases on PyPI
        urllib error: [Errno 101] Network is unreachable
(foo)fab@fab-1015PN:/tmp/foo% ls /tmp/foo/lib/python2.7/site-packages                                                                   
argh-0.14.0-py2.7.egg  hggit                pip-1.0.1-py2.7.egg     pyg.egg-link         setuptools.pth
easy-install.pth       hg_git-0.2.6-py2.7.egg-info  pkgtools-0.6-py2.7.egg  setuptools-0.6c11-py2.7.egg

# That sound OK
(foo)fab@fab-1015PN:/tmp/foo% pyg install hg-git                                                                                        
Loading options from /home/fab/.pyg/pyg.conf
hg-git is already installed, use -U, --upgrade to upgrade

# That is a mistake !!! let's install with -A

(foo)fab@fab-1015PN:/tmp/foo% ls /tmp/foo/lib/python2.7/site-packages                                                                   
argh-0.14.0-py2.7.egg  hggit                pip-1.0.1-py2.7.egg     pyg.egg-link         setuptools.pth
easy-install.pth       hg_git-0.2.6-py2.7.egg-info  pkgtools-0.6-py2.7.egg  setuptools-0.6c11-py2.7.egg
(foo)fab@fab-1015PN:/tmp/foo% pyg install hg-git -A                                                                                     
Loading options from /home/fab/.pyg/pyg.conf
hg-git is already installed, upgrading...
Traceback (most recent call last):
  File "/home/fab/progs/pyg/pyg/__init__.py", line 28, in main
    parser.dispatch()
  File "build/bdist.linux-i686/egg/argh/helpers.py", line 304, in dispatch
  File "build/bdist.linux-i686/egg/argh/helpers.py", line 205, in dispatch
  File "build/bdist.linux-i686/egg/argh/helpers.py", line 281, in _execute_command
  File "build/bdist.linux-i686/egg/argh/helpers.py", line 264, in _call
  File "/home/fab/progs/pyg/pyg/parser/parser.py", line 83, in install
    args_manager['install']['ignore'])
  File "/home/fab/progs/pyg/pyg/parser/_opts.py", line 93, in install_func
    _install_package_from_name(package, ignore)
  File "/home/fab/progs/pyg/pyg/parser/_opts.py", line 73, in _install_package_from_name
    return Installer(package).install()
  File "/home/fab/progs/pyg/pyg/inst.py", line 76, in install
    updater.remove_files(self.req)
  File "/home/fab/progs/pyg/pyg/inst.py", line 335, in remove_files
    uninst.uninstall()
  File "/home/fab/progs/pyg/pyg/inst.py", line 285, in uninstall
    with open(EASY_INSTALL) as f:
IOError: [Errno 2] No such file or directory: '/tmp/foo/lib/python2.7/site-packages/easy-install.pth'

```

Effectively, the `/tmp/foo/lib/python2.7/site-packages` folder is now missing...

**Comment by fdev31** [comment]
I suggest two things we need to discuss:
- pyg may own a simple (& fast) database to keep track of installed packages state (and if they are direct or installed as a dependency)
- pyg may uninstall an incorrectly installed package on error

the second problem is probably related to some "hardcore" uninstallation, I'm going to check that since I have some free time just now :)

**Comment by rubik** [comment]
Argh!! Always the same problem!

I checked your commit, you made very clever changes! As for the database, it would be an interesting idea, but where do we store it? Sometimes we don't even know the home directory's name...
Uninstallation of incorrectly installed packages shouldn't be too difficult.

**Comment by fdev31** [comment]
We can use some "in memory" variables to know if the upgrade/install process of a given package finished entirely or not (so we could be able to do atomic installs/upgrade , not letting things messed up if something wrong happens with some dependency....).
I agree it's preferable to avoid an "on disk" data store with packages status since it will cause maintenance problems (managing pyg PLUS foreign installations at the same time).
I improved some path detection again, I suppose most packagers programs didn't implement uninstall feature because pkg_resources looks very buggy about packages information. We are entering an heuristics world :P
Maybe your pkgtools library could "fix" (or at least improve) pkg_resources providing nice heuristics... so we could move path detection code to it.

**Comment by rubik** [comment]
> We can use some "in memory" variables to know if the upgrade/install process of a given package finished entirely or not > (so we could be able to do atomic installs/upgrade , not letting things messed up if something wrong happens with some dependency....).

We are already doing this (in part):
https://github.com/rubik/pyg/blob/master/pyg/inst.py#L84

Probably we should do that even if a package is being installed for the first time.

> Maybe your pkgtools library could "fix" (or at least improve) pkg_resources providing nice heuristics... so we could move path detection code to it.

That's a nice idea! I'll work on it.

P.S. I set you as pkgtools' collaborator, in case you want to do some experiments! ;)

**Comment by fdev31** [comment]
```
    # Now let's install dependencies
    Installer._install_deps(r.reqset, r.name)
```

=> If we move those lines up (in the "try" statement) it should work as expected, isn't it ?
I mean, dependencies errors are handled outside the exception management (that will roll things back eventually) but it should be seen as part of the installation process (that can be reverted on error).

**Comment by rubik** [comment]
Yes you are right. I think that will fix the issue.

**Comment by rubik** [comment]
We shouldn't roll-back only on upgrading: even on normal installations. I'll fix that now.

**Comment by rubik** [comment]
I tried with your example and it works well. Do you still have the issue?

**Comment by fdev31** [comment]
Still not 100% perfect, I tried to improve it but I'm not happy with the result yet:
http://pastebin.com/fm5nrS3x

**Comment by rubik** [comment]
I think they're good changes, what's missing in your opinion?

**Comment by fdev31** [comment]
Try the latest commit on a fresh virtualenv:

```
pyg install hg-git
```

then ^C when it's installing dulwich. I expect dulwich & hg-git traces to be removed, instead of keeping "stale" packages.
It's not working that way for the "base" package (hg-git), do you understand why It's still installed in a broken way ?

**Comment by rubik** [comment]
I think it is the Updater that is buggy. I'll test Updater.remove_files a bit.

We really should write tests... Maybe we can introduce them in the next release, instead waiting until Pyg 1.0.

**Comment by fdev31** [comment]
Having a minimal test suite could avoid "bad" surprises while releasing :P
