### ISSUE TITLE
Searching for updates and then upgrade

### ISSUE THREAD

**Issue by markon** [rubik/pyg#9]
Maybe this feature is not so easy to implement, but it may be a good feature, since it has not been implemented in easy_install/pip yet.

Usually you decide to manually upgrade a package just after you've known it's not up-to-date. So you first read on the package's homepage that a new version has been released, then you type "pyg --upgrade package".

It may be a useful feature to have an option that checks for updates automatically and then asks users for confirmation to upgrade every package.

Maybe the following example will explain it better.
I've 2 packages installed by using pyg: django-1.0.0 and django-tagging-0.2. 
As you may see, they're old versions.
pyg --check # THIS WILL OUTPUT

Your django package is not up-to-date. 
There are more recent packages. Please choose a version to upgrade your django package, or type NO to continue using the old version.
0 : django-1.1.0
1:  django-1.2.3
2:  django-1.2.4
3:  django-1.3.0

Choose [NO]: # the default option is to not upgrade.

Your django-tagging package is not up-to-date.
There is a new up-to-date package. Please type YES if you want to upgrade, or NO if you don't.
NEW: django-tagging-0.3.1
Choose [NO]: # the default option is to not upgrade.

**Comment by rubik** [comment]
It is good idea, indeed. But I think we will implement it in the next releases!

**Comment by rubik** [comment]
I've thought about it: one can have hundred of packages installed... checking and upgrading takes a lot of time.

**Comment by markon** [comment]
What's the matter?

You may think about pyg like "apt". 
Whenever you run "apt-get update" it searches for new updates and then stores the result in its cache. Then you run "upgrade" and it asks if you want to upgrade the packages. 
The same can happen if you run "pyg update" that searches for new updates. If so, you can save updates in a file, as:
[package]
installed = django-tagging-0.2
updates = [django-tagging-0.3.0, django-tagging-0.3.1, ...]
[package]
...
[package]
...

**Comment by rubik** [comment]
Ok, I'm working on it. This is how it looks (I still have to commit the changes):

```
$ pyg update
Loading list of installed packages...
Searching for updates
A new release is avaiable for simplejson: 2.1.3 (old 2.1.2)
Do you want to upgrade? (y/[n])
simplejson has not been upgraded
A new release is avaiable for oauth: 1.0 (old 1.0a)
Do you want to upgrade? (y/[n])
oauth has not been upgraded
A new release is avaiable for wadllib: 1.2.0 (old 1.1.8)
Do you want to upgrade? (y/[n])
wadllib has not been upgraded
A new release is avaiable for rdflib: 3.1.0 (old 2.4.2)
Do you want to upgrade? (y/[n])
rdflib has not been upgraded
A new release is avaiable for pip: 1.0 (old 0.8.3)
Do you want to upgrade? (y/[n])
pip has not been upgraded
A new release is avaiable for launchpadlib: 1.9.8 (old 1.9.7)
Do you want to upgrade? (y/[n])
launchpadlib has not been upgraded
A new release is avaiable for configglue: 0.9.1 (old 0.9pre1)
Do you want to upgrade? (y/[n])
configglue has not been upgraded
Updating finished successfully
```

I answered `no` all the times.

**Comment by rubik** [comment]
I have tried to install a couple of packages and it seems to work (WoW!):

```
$ pyg update
Loading list of installed packages...
Searching for updates
A new release is avaiable for simplejson: 2.1.3 (old 2.1.2)
Do you want to upgrade? (y/[n])y
Upgrading simplejson to 2.1.3
        Installing simplejson-2.1.3.tar.gz...
            Installing simplejson-2.1.3.tar.gz
            Running setup.py install for simplejson
            Installing dependencies...
Finished installing dependencies
simplejson installed successfully
...
A new release is avaiable for pip: 1.0 (old 0.8.3)
Do you want to upgrade? (y/[n])y
Upgrading pip to 1.0
        Installing pip-1.0.tar.gz...
            Installing pip-1.0.tar.gz
            Running setup.py install for pip
            Installing dependencies...
Finished installing dependencies
pip installed successfully
```

**Comment by rubik** [comment]
Ok now I commit, but it needs the `WorkingSet` class, that is in `pkgtools.pkg`:
https://github.com/rubik/pkgtools
