### ISSUE TITLE
Zicbee Pack

### ISSUE THREAD

**Issue by rubik** [rubik/pyg#90]
Pyg should be able to create Packs... (See #85)

**Comment by fdev31** [comment]
About the name, why not just .zip ?
A file containing a folder with package's name, itself containing two files:
- run.py
- <package's name>.egg

**Comment by rubik** [comment]
Yes! I overcomplicated things, .zip is just right!
Only one more thing, it is not clear to me what `run.py` should contain. How do we know what to run?

**Comment by fdev31** [comment]
Just clone https://github.com/fdev31/zicbee-workshop and run "manage" code, most interesting is:
https://github.com/fdev31/zicbee-workshop/blob/master/_genexecutables.py which is a base...
For the paths to look for the ".egg" we may discuss... We could also make a run command that could rewrite itself this way:

```
./run.py --pkg-egg ~/myapps/myprogram.egg
```

and even

```
./run.py --pkg-install
```

:)

**Comment by fdev31** [comment]
I could have fun writing the launcher & his generator but I'm little out of time right now :P
If you get a working egg generation that could replace mine I'll eventually dive into it :)

**Comment by rubik** [comment]
Thank you for the links, I didn't see that there was `_genexecutable.py` too! :)
pyg.pack.Packer actually works well, only launcher generation is missing! We could just add to `sys.path` our egg. The zipimport module is included in stdlib from version 2.3, it wouldn't be difficult.

**Comment by fdev31** [comment]
First bug ;)

```
% python pyg/pack.py zicbee-lib

zicbee-lib:
        Retrieving data for zicbee-lib [100% - 22.1 Kb / 22.1 Kb]              
        Writing data into zicbee-lib-0.7.3.tar.gz
        zicbee-lib downloaded successfully
        Looking for zicbee-lib dependencies
Finished processing dependencies
Adding packages to the bundle
```

**Comment by rubik** [comment]
But zicbee-lib does not have a requires.txt file! :)

**Comment by fdev31** [comment]
Because It has no requirement :P

**Comment by rubik** [comment]
LOL so what is the bug? XD

**Comment by rubik** [comment]
I've just realized that entry_points is formatted wrongly and spec/depend has a wrong version. I'll fix that now.

**Comment by rubik** [comment]
OOps double commit is due to the automatic merge...

**Comment by fdev31** [comment]
If I need some kind of advanced configuration (to help the creation of the .py file or to auto-remove files from the archive for instance) would you recommend sticking to .ini format or is it possible to ask the user for values and/or propose an alternative configuration file ?

**Comment by rubik** [comment]
So, if we decided to postpone advanced features to next release, I think I can close this issue and open a new one later.

**Comment by fdev31** [comment]
Just set the feat. For the release after... It's not working yet...

Le 14 juil. 2011 20:34, "rubik" <
reply@reply.github.com> a
crit :

So, if we decided to postpone advanced features to next release, I think I
can close this issue.

##

**Comment by rubik** [comment]
So I'll open a new issue...
