### ISSUE TITLE
Replace `pyg freeze` with `pyg site`

### ISSUE THREAD

**Issue by rubik** [rubik/pyg#91]
This new command should show some site information as well...

**Comment by rubik** [comment]
Currently `pyg site` shows information about Python and Pyg versions, sys.prefix, and the platform. What other information should we provide?

**Comment by fdev31** [comment]
I think it's OK now, maybe providing a list of PATHS can help too but we can still improve things if people ask for it :)

**Comment by fdev31** [comment]
It could tell if running from a virtual environment or not...

**Comment by rubik** [comment]
Yes, that's interesting, I'll commit it now.

**Comment by rubik** [comment]
Yes, that's interesting, I'll commit it now.
