### ISSUE TITLE
Bundle error when bundling same packages

### ISSUE THREAD

**Issue by rubik** [rubik/pyg#94]
I didn't know how to explain in the title, but try this:

```
$ echo -e "pyg\npkgtools" > r.txt
$ pyg bundle pyg.pyb -r r.txt
```

`pkgtools` is in pyg dependencies and in the requirements file, so Pyg tries to download it twice... This should be easy to fix.

**Comment by fdev31** [comment]
See latest errors, seems that "pyb" is back in "pack" command... 
http://zicbee.gnux.info:8010/builders/pyg/builds/13/steps/building/logs/stdio

**Comment by rubik** [comment]
I don't have that error... I think it has been introduced in the last commit...

**Comment by rubik** [comment]
Argh, that's true! If you keep multiple items on the same `with`, it works. Otherwise, it doesn't. 
Damned Python2.6!

**Comment by fdev31** [comment]
Hmmm... probably the double "with" refactor, I'll check :)

**Comment by rubik** [comment]
After this commit: https://github.com/rubik/pyg/commit/e7dcc1dc1232c5feb8fd791876f730fa52fb23a2
It works, it was an indentation problem... :)

**Comment by rubik** [comment]
Wow simultaneous post! :)
